import AppIntents

/// App Shortcuts: available in Siri, Spotlight and the Shortcuts app as soon
/// as TaskLens is installed. Phrases must name the app; their Arabic forms
/// are in `Resources/AppShortcuts.xcstrings` (generated by scripts/strings.py).
struct TaskLensShortcuts: AppShortcutsProvider {
    /// iOS allows at most 10 App Shortcuts per app.
    static let maximumShortcuts = 10

    static var appShortcuts: [AppShortcut] {
        AppShortcut(
            intent: SendToTaskLensIntent(),
            phrases: [
                "Send to \(.applicationName)",
                "Analyze with \(.applicationName)",
            ],
            shortTitle: "intent.sendToTaskLens.title",
            systemImageName: "paperplane"
        )
        AppShortcut(
            intent: StartWorkspaceIntent(),
            phrases: [
                "Start \(\.$kind) workspace in \(.applicationName)",
                "Start a workspace in \(.applicationName)",
            ],
            shortTitle: "intent.startWorkspace.title",
            systemImageName: "square.grid.2x2"
        )
        AppShortcut(
            intent: SaveContentIntent(),
            phrases: ["Save to \(.applicationName)"],
            shortTitle: "intent.saveContent.title",
            systemImageName: "tray.and.arrow.down"
        )
        AppShortcut(
            intent: SaveToSessionIntent(),
            phrases: [
                "Save to \(\.$sessionKind) session in \(.applicationName)",
                "Save to a session in \(.applicationName)",
            ],
            shortTitle: "intent.saveToSession.title",
            systemImageName: "tray.full"
        )
        AppShortcut(
            intent: StartLensIntent(),
            phrases: [
                "Start \(.applicationName) Lens",
                "Open Lens in \(.applicationName)",
            ],
            shortTitle: "intent.startLens.title",
            systemImageName: "viewfinder"
        )
        AppShortcut(
            intent: CreateNoteIntent(),
            phrases: [
                "Create \(.applicationName) note",
                "New note in \(.applicationName)",
            ],
            shortTitle: "intent.createNote.title",
            systemImageName: "note.text.badge.plus"
        )
        AppShortcut(
            intent: OpenClipboardIntent(),
            phrases: ["Open \(.applicationName) clipboard"],
            shortTitle: "intent.openClipboard.title",
            systemImageName: "doc.on.clipboard"
        )
        AppShortcut(
            intent: CalculateIntent(),
            phrases: ["Calculate with \(.applicationName)"],
            shortTitle: "intent.calculate.title",
            systemImageName: "plus.forwardslash.minus"
        )
        AppShortcut(
            intent: OpenSessionIntent(),
            phrases: ["Open a session in \(.applicationName)"],
            shortTitle: "intent.openSession.title",
            systemImageName: "clock.arrow.circlepath"
        )
        AppShortcut(
            intent: StartSessionIntent(),
            phrases: ["Start a \(.applicationName) session"],
            shortTitle: "intent.startSession.title",
            systemImageName: "play.circle"
        )
    }
}
