#!/usr/bin/env python3
"""Single source of truth for TaskLens UI strings.

Running this script regenerates:
  Packages/TaskLensUI/Sources/TLLocalization/Resources/Localizable.xcstrings
  Packages/TaskLensUI/Sources/TLLocalization/L10nKey.swift
  App/TaskLens/Resources/Localizable.xcstrings   (App Intents metadata)
  App/TaskLens/Resources/AppShortcuts.xcstrings  (App Shortcut phrases)

Add a key here (with both English and Arabic) instead of editing those files.
"""
import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
LOC = ROOT / "Packages/TaskLensUI/Sources/TLLocalization"

STRINGS = [
    # key, English, Arabic
    ("tab.commandCenter", "Command Center", "مركز الأوامر"),
    ("tab.workspaces", "Workspaces", "مساحات العمل"),
    ("tab.settings", "Settings", "الإعدادات"),

    ("common.cancel", "Cancel", "إلغاء"),
    ("common.create", "Create", "إنشاء"),
    ("common.delete", "Delete", "حذف"),
    ("common.ok", "OK", "حسناً"),
    ("common.save", "Save", "حفظ"),
    ("common.more", "More", "المزيد"),
    ("common.errorTitle", "Something went wrong", "حدث خطأ"),
    ("common.continue", "Continue", "متابعة"),

    ("capture.placeholder", "Type or paste something…", "اكتب أو الصق شيئاً…"),
    ("capture.inbox", "Inbox", "الوارد"),

    ("commandCenter.activeSessions", "Active Sessions", "الجلسات النشطة"),
    ("commandCenter.recentItems", "Recent Items", "العناصر الأخيرة"),
    ("commandCenter.quickCapture", "Quick Capture", "التقاط سريع"),
    ("commandCenter.savesTo", "Saves to the most recent active session, or the inbox.",
     "يُحفظ في آخر جلسة نشطة، أو في الوارد."),
    ("commandCenter.empty.title", "Nothing captured yet", "لم يتم التقاط شيء بعد"),
    ("commandCenter.empty.message", "Type or paste content above to get started.",
     "اكتب أو الصق محتوى في الأعلى للبدء."),

    ("workspaces.create", "New Workspace", "مساحة عمل جديدة"),
    ("workspaces.name", "Name", "الاسم"),
    ("workspaces.color", "Color", "اللون"),
    ("workspaces.archive", "Archive", "أرشفة"),
    ("workspaces.empty.title", "No workspaces", "لا توجد مساحات عمل"),
    ("workspaces.empty.message", "Create a workspace to group your sessions.",
     "أنشئ مساحة عمل لتجميع جلساتك."),
    ("workspace.sessions", "Sessions", "الجلسات"),
    ("workspace.startSession", "Start Session", "بدء جلسة"),
    ("workspace.noSessions.title", "No sessions yet", "لا توجد جلسات بعد"),
    ("workspace.noSessions.message", "Start a session to collect what you are working on.",
     "ابدأ جلسة لتجميع ما تعمل عليه."),

    ("session.untitled", "Untitled Session", "جلسة بدون عنوان"),
    ("session.items", "Items", "العناصر"),
    ("session.noItems.title", "No items yet", "لا توجد عناصر بعد"),
    ("session.noItems.message", "Anything you capture in this session appears here.",
     "كل ما تلتقطه في هذه الجلسة يظهر هنا."),
    ("session.end", "End Session", "إنهاء الجلسة"),
    ("session.pause", "Pause", "إيقاف مؤقت"),
    ("session.resume", "Resume", "استئناف"),
    ("session.startedAt", "Started", "بدأت"),
    ("session.state.active", "Active", "نشطة"),
    ("session.state.paused", "Paused", "متوقفة مؤقتاً"),
    ("session.state.ended", "Ended", "منتهية"),
    ("session.kind.general", "General", "عامة"),
    ("session.kind.research", "Research", "بحث"),
    ("session.kind.shopping", "Shopping", "تسوق"),
    ("session.kind.study", "Study", "دراسة"),
    ("session.kind.developer", "Developer", "تطوير"),
    ("session.kind.other", "Other", "أخرى"),
    ("session.state.archived", "Archived", "مؤرشفة"),
    ("session.favorite", "Add to Favorites", "إضافة إلى المفضلة"),
    ("session.unfavorite", "Remove from Favorites", "إزالة من المفضلة"),
    ("session.archive", "Archive", "أرشفة"),
    ("session.unarchive", "Unarchive", "إلغاء الأرشفة"),
    ("session.rename", "Rename", "إعادة تسمية"),
    ("session.name", "Session name", "اسم الجلسة"),
    ("session.delete", "Delete Session", "حذف الجلسة"),
    ("session.deleteMessage", "The session, its items and its action history will be deleted. Notes stay in Notes.",
     "ستُحذف الجلسة وعناصرها وسجل إجراءاتها. تبقى الملاحظات في الملاحظات."),
    ("session.favorites", "Favorites", "المفضلة"),
    ("session.archived", "Archived", "المؤرشفة"),
    ("session.lastActivity", "Last activity", "آخر نشاط"),
    ("session.pickUp", "Pick Up Where You Left Off", "تابع من حيث توقفت"),
    ("session.pickUpNote", "This restores your TaskLens session only. Other apps open as they are.",
     "يستعيد هذا جلسة TaskLens فقط. التطبيقات الأخرى تفتح كما هي."),
    ("session.resume.page", "Open the last web page", "افتح آخر صفحة ويب"),
    ("session.resume.document", "Open the document at page %lld", "افتح المستند عند الصفحة %lld"),
    ("session.resume.note", "Open the last note", "افتح آخر ملاحظة"),
    ("session.resume.tool", "Open the last tool", "افتح آخر أداة"),
    ("session.sort", "Sort", "الترتيب"),
    ("session.sort.recent", "Recent", "الأحدث"),
    ("session.sort.type", "Type", "النوع"),
    ("session.sort.importance", "Importance", "الأهمية"),
    ("session.searchPrompt", "Search this session", "ابحث في هذه الجلسة"),
    ("session.actionHistory", "Action History", "سجل الإجراءات"),
    ("session.markImportant", "Mark as Important", "تمييز كمهم"),
    ("session.unmarkImportant", "Remove Important Mark", "إزالة تمييز الأهمية"),
    ("session.important", "Important", "مهم"),
    ("session.itemKind.note", "Notes", "ملاحظات"),
    ("session.itemKind.link", "Links", "روابط"),
    ("session.itemKind.document", "Documents", "مستندات"),
    ("session.itemKind.image", "Images", "صور"),
    ("session.itemKind.calculation", "Calculations", "حسابات"),
    ("session.itemKind.code", "Code", "شيفرة"),
    ("session.itemKind.question", "Questions", "أسئلة"),
    ("session.itemKind.clipboard", "Clipboard", "الحافظة"),
    ("session.itemKind.text", "Text", "نصوص"),
    ("actionRecord.completed", "Done", "تم"),
    ("actionRecord.handedOff", "Opened", "فُتح"),
    ("actionRecord.failed", "Failed", "فشل"),
    # Widgets and Siri
    ("widget.name", "TaskLens", "TaskLens"),
    ("widget.description", "Quick actions, recent sessions and your workspace.", "إجراءات سريعة وآخر الجلسات ومساحة عملك."),
    ("widget.recentSessions", "Recent Sessions", "آخر الجلسات"),
    ("widget.noSessions", "No sessions yet. Start one in TaskLens.", "لا توجد جلسات بعد. ابدأ واحدة في TaskLens."),
    ("widget.noWorkspaces", "Open TaskLens to create a workspace.", "افتح TaskLens لإنشاء مساحة عمل."),
    ("widget.itemCount", "%lld items", "%lld عناصر"),

    # Live Activity and Dynamic Island.
    ("activity.sessionTitle", "%@ Session", "جلسة %@"),
    ("activity.links", "Links: %lld", "الروابط: %lld"),
    ("activity.notes", "Notes: %lld", "الملاحظات: %lld"),
    ("activity.documents", "Documents: %lld", "المستندات: %lld"),
    ("activity.items", "Items: %lld", "العناصر: %lld"),
    ("activity.processing", "Processing", "قيد المعالجة"),
    ("activity.focus", "Focus", "تركيز"),
    ("activity.task", "Active Task", "المهمة الحالية"),
    ("activity.elapsed", "Elapsed", "المدة"),
    ("activity.remaining", "Remaining", "المتبقي"),
    ("activity.resume", "Resume", "استئناف"),
    ("activity.stop", "Stop", "إيقاف"),
    ("activity.stale", "No recent activity", "لا يوجد نشاط حديث"),
    ("session.focus", "Focus Timer", "مؤقت التركيز"),
    ("session.focus.minutes", "%lld minutes", "%lld دقيقة"),
    ("session.focus.stop", "Stop Focus Timer", "إيقاف مؤقت التركيز"),

    # What Siri and Shortcuts say back after an action.
    ("intent.result.savedToSession", "Saved to %@.", "تم الحفظ في %@."),
    ("intent.result.savedToInbox", "Saved to the inbox.", "تم الحفظ في الوارد."),
    ("intent.result.noteCreated", "Note created: %@", "تم إنشاء الملاحظة: %@"),
    ("intent.result.equals", "%@ = %@", "%@ = %@"),
    # Picture in Picture
    ("pip.title", "Picture in Picture", "صورة داخل صورة"),
    ("pip.keep", "Keep in Picture in Picture", "إبقاء في صورة داخل صورة"),
    ("pip.page", "Page %lld", "صفحة %lld"),
    ("pip.emptyCard", "Add a note, a page or a result to keep it in view.", "أضف ملاحظة أو صفحة أو نتيجة لتبقى أمامك."),
    ("pip.kind.note", "Note", "ملاحظة"),
    ("pip.kind.document", "Document", "مستند"),
    ("pip.kind.calculation", "Calculation", "عملية حسابية"),
    ("pip.kind.context", "Context", "سياق"),
    ("pip.status", "Window", "النافذة"),
    ("pip.status.idle", "Closed", "مغلقة"),
    ("pip.status.unavailable", "Not available right now", "غير متاحة الآن"),
    ("pip.status.starting", "Opening…", "جارٍ الفتح…"),
    ("pip.status.active", "Showing", "معروضة"),
    ("pip.status.stopping", "Closing…", "جارٍ الإغلاق…"),
    ("pip.start", "Start Picture in Picture", "بدء صورة داخل صورة"),
    ("pip.stop", "Stop Picture in Picture", "إيقاف صورة داخل صورة"),
    ("pip.previous", "Previous Card", "البطاقة السابقة"),
    ("pip.next", "Next Card", "البطاقة التالية"),
    ("pip.showing", "Showing", "معروضة"),
    ("pip.cards", "Cards", "البطاقات"),
    ("pip.cards.hint", "Use Keep in Picture in Picture from a note, a document page, the calculator or a session item. Tap a card to show it.", "استخدم «إبقاء في صورة داخل صورة» من ملاحظة أو صفحة مستند أو الحاسبة أو عنصر جلسة. اضغط بطاقة لعرضها."),
    ("pip.noCards", "No cards yet", "لا توجد بطاقات بعد"),
    ("pip.unsupported.title", "Not supported on this device", "غير مدعومة على هذا الجهاز"),
    ("pip.unsupported.message", "This device does not offer Picture in Picture. Your cards stay here in TaskLens.", "هذا الجهاز لا يوفر صورة داخل صورة. تبقى بطاقاتك هنا داخل TaskLens."),
    ("pip.limits.title", "What Picture in Picture can do", "ما الذي تستطيعه صورة داخل صورة"),
    ("pip.limit.readOnly", "The window shows one card as a picture. You can move it, resize it, hide it at the edge and tap it to return here. You cannot type or tap inside it; change cards here and the window follows.", "تعرض النافذة بطاقة واحدة كصورة. يمكنك تحريكها وتغيير حجمها وإخفاءها عند الحافة والضغط عليها للعودة. لا يمكن الكتابة أو الضغط داخلها؛ غيّر البطاقة من هنا وستتبعها النافذة."),
    ("pip.limit.ownContent", "It shows TaskLens content only. It cannot place controls over other apps or read what they show.", "تعرض محتوى TaskLens فقط. لا يمكنها وضع عناصر تحكم فوق التطبيقات الأخرى أو قراءة ما تعرضه."),
    ("pip.limit.start", "iOS opens it only from TaskLens: when you tap Start, or when you leave the app while this screen is open (if automatic Picture in Picture is on in Settings).", "يفتحها iOS من داخل TaskLens فقط: عند الضغط على «بدء»، أو عند مغادرة التطبيق وهذه الشاشة مفتوحة (إذا كانت صورة داخل صورة التلقائية مفعّلة في الإعدادات)."),
    ("pip.limit.closed", "It closes when TaskLens is closed, and iOS may close it for a call or another video. Your cards are kept.", "تُغلق عند إغلاق TaskLens، وقد يغلقها iOS بسبب مكالمة أو فيديو آخر. بطاقاتك محفوظة."),
    ("pip.stopped.user", "Picture in Picture was closed.", "أُغلقت صورة داخل صورة."),
    ("pip.stopped.restored", "Returned from Picture in Picture.", "تمت العودة من صورة داخل صورة."),
    ("pip.stopped.interrupted", "iOS closed Picture in Picture for a call or other audio. Start it again when you are ready.", "أغلق iOS صورة داخل صورة بسبب مكالمة أو صوت آخر. ابدأها مجدداً عندما تكون جاهزاً."),
    ("pip.stopped.failed", "Picture in Picture could not open. Another app may be using it.", "تعذّر فتح صورة داخل صورة. ربما يستخدمها تطبيق آخر."),
    ("pip.stopped.appClosed", "Picture in Picture ended when TaskLens was closed. Your cards are still here.", "انتهت صورة داخل صورة عند إغلاق TaskLens. بطاقاتك ما زالت هنا."),

    ("item.type.text", "Text", "نص"),
    ("item.type.url", "Link", "رابط"),
    ("item.type.image", "Image", "صورة"),
    ("item.type.pdf", "PDF", "PDF"),
    ("item.type.document", "Document", "مستند"),

    ("settings.about", "About", "حول"),
    ("settings.version", "Version", "الإصدار"),
    ("settings.privacy", "Privacy", "الخصوصية"),
    ("settings.privacy.body",
     "TaskLens only processes content you explicitly type, paste, share or capture. Your data stays on this device.",
     "يعالج TaskLens فقط المحتوى الذي تكتبه أو تلصقه أو تشاركه أو تلتقطه بنفسك. تبقى بياناتك على هذا الجهاز."),
    ("settings.language", "Language", "اللغة"),
    ("settings.language.body", "TaskLens follows the language chosen for it in iOS Settings.",
     "يتبع TaskLens اللغة المختارة له في إعدادات iOS."),
    ("settings.openSettings", "Open iOS Settings", "فتح إعدادات iOS"),
    ("settings.liveActivitiesOff", "Live Activities are off for TaskLens, so sessions don't show on the Lock Screen. You can turn them on in iOS Settings.", "الأنشطة المباشرة متوقفة لتطبيق TaskLens، لذلك لا تظهر الجلسات على شاشة القفل. يمكنك تشغيلها من إعدادات iOS."),
    ("settings.storage", "Storage", "التخزين"),
    ("settings.storage.appGroup", "Shared app container", "حاوية التطبيق المشتركة"),
    ("settings.storage.local", "Local app storage", "تخزين التطبيق المحلي"),
    ("settings.storage.memory", "Temporary, not saved", "مؤقت وغير محفوظ"),

    ("common.edit", "Edit", "تعديل"),
    ("common.duplicate", "Duplicate", "تكرار"),
    ("common.favorite", "Add to Favorites", "إضافة إلى المفضلة"),
    ("common.unfavorite", "Remove from Favorites", "إزالة من المفضلة"),
    ("common.done", "Done", "تم"),

    ("commandCenter.quickActions", "Quick Actions", "إجراءات سريعة"),
    ("commandCenter.seeAll", "See All", "عرض الكل"),
    ("commandCenter.recentSessions", "Recent Sessions", "الجلسات الأخيرة"),
    ("commandCenter.searchPrompt", "Search notes, links, documents and more",
     "ابحث في الملاحظات والروابط والمستندات وغيرها"),
    ("commandCenter.noWorkspaces", "Create your first workspace to organize your work.",
     "أنشئ أول مساحة عمل لتنظيم عملك."),

    ("search.kind.workspace", "Workspace", "مساحة عمل"),
    ("search.kind.session", "Session", "جلسة"),
    ("search.kind.item", "Saved item", "عنصر محفوظ"),
    ("search.kind.note", "Note", "ملاحظة"),
    ("search.kind.document", "Document", "مستند"),
    ("search.kind.clipboard", "Clipboard", "الحافظة"),
    ("search.meaning", "Similar meaning", "معنى مشابه"),
    ("search.lookingFor", "Looking for", "تبحث عن"),
    ("search.onDevice", "Search runs on this iPhone. Nothing is sent.",
     "يتم البحث على هذا الآيفون. لا يُرسل أي شيء."),
    ("search.onDeviceMeaning", "Search runs on this iPhone, by words and by meaning. Nothing is sent.",
     "يتم البحث على هذا الآيفون بالكلمات وبالمعنى. لا يُرسل أي شيء."),
    ("search.filter.link", "Links", "روابط"),
    ("search.filter.note", "Notes", "ملاحظات"),
    ("search.filter.document", "Documents", "مستندات"),
    ("search.filter.pdf", "PDF", "PDF"),
    ("search.filter.image", "Images", "صور"),
    ("search.filter.text", "Texts", "نصوص"),
    ("search.filter.clipboard", "Clipboard", "الحافظة"),
    ("search.filter.price", "Prices", "أسعار"),
    ("search.filter.phone", "Phone numbers", "أرقام هواتف"),
    ("search.filter.email", "Emails", "بريد إلكتروني"),
    ("search.filter.date", "Dates", "تواريخ"),
    ("search.filter.address", "Addresses", "عناوين"),
    ("search.filter.code", "Code", "كود"),

    ("settings.data", "Your Data", "بياناتك"),
    ("settings.data.export", "Export a Copy", "تصدير نسخة"),
    ("settings.data.shareExport", "Share Export File", "مشاركة ملف التصدير"),
    ("settings.data.deleteAll", "Delete All Data", "حذف كل البيانات"),
    ("settings.data.deleteAllTitle", "Delete all TaskLens data?", "حذف كل بيانات TaskLens؟"),
    ("settings.data.deleteAllMessage", "Workspaces, sessions, notes, documents, clipboard, history, workflows and the AI server key are deleted from this iPhone. This can't be undone.",
     "ستُحذف مساحات العمل والجلسات والملاحظات والمستندات والحافظة والسجل وسير العمل ومفتاح خادم الذكاء الاصطناعي من هذا الآيفون. لا يمكن التراجع."),
    ("settings.data.deleted", "All data was deleted.", "تم حذف كل البيانات."),
    ("settings.data.footer", "The export is a JSON file of your workspaces, sessions, notes, history and workflows. Imported files stay on this iPhone. TaskLens doesn't sync to iCloud; your data is included in your device backup.",
     "التصدير ملف JSON يضم مساحات العمل والجلسات والملاحظات والسجل وسير العمل. تبقى الملفات المستوردة على هذا الآيفون. لا يتزامن TaskLens مع iCloud، وبياناتك ضمن النسخة الاحتياطية لجهازك."),

    ("workflows.title", "Workflows", "سير العمل"),
    ("workflows.new", "New Workflow", "سير عمل جديد"),
    ("workflows.templates", "Ready-made", "جاهزة"),
    ("workflows.template.0", "Save links to Research", "حفظ الروابط في البحث"),
    ("workflows.template.1", "Summarize a link", "تلخيص رابط"),
    ("workflows.template.2", "Image to text", "من صورة إلى نص"),
    ("workflows.template.3", "Translate an image", "ترجمة صورة"),
    ("workflows.template.4", "Convert to IQD", "تحويل إلى الدينار العراقي"),
    ("workflows.template.5", "PDF to notes", "من PDF إلى ملاحظات"),
    ("workflows.copyName", "%@ copy", "نسخة من %@"),
    ("workflows.empty", "No workflows yet. Add one, or start from a ready-made one.",
     "لا يوجد سير عمل بعد. أضف واحداً أو ابدأ من سير عمل جاهز."),
    ("workflows.footer", "Turned-on workflows run when you share matching content to TaskLens. Tap a workflow to run it yourself.",
     "يعمل سير العمل المفعّل عندما تشارك محتوى مطابقاً مع TaskLens. اضغط على سير عمل لتشغيله بنفسك."),
    ("workflows.pending", "Waiting for your OK", "بانتظار موافقتك"),
    ("workflows.pending.footer", "These workflows use AI, so they run only after you confirm.",
     "تستخدم هذه الأعمال الذكاء الاصطناعي، لذلك لا تعمل إلا بعد تأكيدك."),
    ("workflows.asksFirst", "Asks before running", "يطلب الإذن قبل التشغيل"),
    ("workflows.confirm.title", "Run this workflow?", "تشغيل سير العمل هذا؟"),
    ("workflows.confirm.message", "It uses AI. If AI runs on your server, the text is sent there. Nothing runs until you confirm.",
     "يستخدم الذكاء الاصطناعي. إذا كان يعمل على خادمك فسيُرسل النص إليه. لا يُنفَّذ شيء قبل تأكيدك."),
    ("workflows.confirm.run", "Run", "تشغيل"),
    ("workflows.dismiss", "Not Now", "ليس الآن"),
    ("workflows.run", "Run", "تشغيل"),
    ("workflows.failed", "This step didn't work. The others still ran.", "لم تنجح هذه الخطوة. نُفّذت الخطوات الأخرى."),
    ("workflows.result", "Result", "النتيجة"),
    ("workflows.result.title", "Result: %@", "النتيجة: %@"),
    ("workflows.result.saved", "Saved in TaskLens", "تم الحفظ في TaskLens"),
    ("workflows.inputPlaceholder", "Text or link to run on", "نص أو رابط لتشغيله عليه"),
    ("workflows.editor.name", "Name", "الاسم"),
    ("workflows.editor.trigger", "Starts when", "يبدأ عند"),
    ("workflows.editor.steps", "Steps", "الخطوات"),
    ("workflows.editor.addStep", "Add Step", "إضافة خطوة"),
    ("workflows.editor.workspace", "Workspace (optional)", "مساحة العمل (اختياري)"),
    ("workflows.editor.currency", "To currency, e.g. IQD", "إلى عملة، مثل IQD"),
    ("workflows.editor.rate", "Rate, e.g. 1310", "سعر الصرف، مثل 1310"),
    ("workflows.editor.rateFooter", "Enter the rate yourself. TaskLens doesn't fetch exchange rates.",
     "أدخل سعر الصرف بنفسك. لا يجلب TaskLens أسعار الصرف."),
    ("workflows.editor.sensitiveFooter", "AI steps ask for your OK every time before the workflow runs.",
     "خطوات الذكاء الاصطناعي تطلب موافقتك في كل مرة قبل التشغيل."),
    ("workflow.trigger.manual", "I tap Run", "أضغط تشغيل"),
    ("workflow.trigger.sharedURL", "I share a link", "أشارك رابطاً"),
    ("workflow.trigger.sharedImage", "I share an image", "أشارك صورة"),
    ("workflow.trigger.sharedText", "I share text", "أشارك نصاً"),
    ("workflow.trigger.sharedPDF", "I share a PDF", "أشارك ملف PDF"),
    ("workflow.trigger.currency", "I share a price", "أشارك سعراً"),
    ("workflow.step.recognizeText", "Read text (OCR)", "قراءة النص (OCR)"),
    ("workflow.step.extract", "Extract", "استخراج"),
    ("workflow.step.convertCurrency", "Convert currency", "تحويل العملة"),
    ("workflow.step.calculate", "Calculate", "حساب"),
    ("workflow.step.summarize", "Summarize (AI)", "تلخيص (ذكاء اصطناعي)"),
    ("workflow.step.translate", "Translate (AI)", "ترجمة (ذكاء اصطناعي)"),
    ("workflow.step.generateNotes", "Make notes (AI)", "إنشاء ملاحظات (ذكاء اصطناعي)"),
    ("workflow.step.createNote", "Create note", "إنشاء ملاحظة"),
    ("workflow.step.save", "Save", "حفظ"),
    ("workflow.skip.noText", "Skipped: no text.", "تم التخطي: لا يوجد نص."),
    ("workflow.skip.notAnImage", "Skipped: not an image.", "تم التخطي: ليست صورة."),
    ("workflow.skip.noAmount", "Skipped: no amount found.", "تم التخطي: لم يُعثر على مبلغ."),
    ("workflow.skip.noRate", "Skipped: add a rate to this step.", "تم التخطي: أضف سعر صرف لهذه الخطوة."),
    ("workflow.skip.nothingToCalculate", "Skipped: nothing to calculate.", "تم التخطي: لا شيء للحساب."),
    ("workflow.skip.aiTurnedOff", "Skipped: AI is off in Settings.", "تم التخطي: الذكاء الاصطناعي متوقف في الإعدادات."),
    ("workflow.skip.aiUnavailable", "Skipped: AI isn't available on this iPhone.", "تم التخطي: الذكاء الاصطناعي غير متاح على هذا الآيفون."),
    ("workflow.skip.aiOffline", "Skipped: you're offline. Run it again later.", "تم التخطي: لا يوجد اتصال. شغّله لاحقاً."),

    ("workspaces.favorites", "Favorites", "المفضلة"),
    ("workspaces.recent", "Recently Opened", "المفتوحة مؤخراً"),
    ("workspace.color.blue", "Blue", "أزرق"),
    ("workspace.color.green", "Green", "أخضر"),
    ("workspace.color.orange", "Orange", "برتقالي"),
    ("workspace.color.purple", "Purple", "بنفسجي"),
    ("workspace.color.pink", "Pink", "وردي"),
    ("workspace.color.teal", "Teal", "أزرق مخضر"),
    ("workspace.color.gray", "Gray", "رمادي"),
    ("workspace.kind.study", "Study", "دراسة"),
    ("workspace.kind.work", "Work", "عمل"),
    ("workspace.kind.shopping", "Shopping", "تسوق"),
    ("workspace.kind.developer", "Developer", "تطوير"),
    ("workspace.kind.custom", "Custom", "مخصصة"),
    ("workspace.kind.research", "Research", "بحث"),
    ("workspace.tools", "Tools", "الأدوات"),
    ("workspace.tool.notes", "Notes", "الملاحظات"),
    ("workspace.tool.calculator", "Calculator", "الآلة الحاسبة"),
    ("workspace.tool.browser", "Browser", "المتصفح"),
    ("workspace.tool.documents", "Documents", "المستندات"),
    ("workspace.tool.clipboard", "Clipboard", "الحافظة"),
    ("workspace.tool.lens", "Lens", "العدسة"),
    ("workspace.tool.other", "Tool", "أداة"),
    ("workspace.tool.upcoming", "Available in a later update", "متاحة في تحديث لاحق"),
    ("workspace.lastOpened", "Last opened", "آخر فتح"),
    ("workspace.neverOpened", "Not opened yet", "لم تُفتح بعد"),
    ("workspace.copyName", "%@ Copy", "نسخة من %@"),
    ("workspace.delete.title", "Delete this workspace?", "حذف مساحة العمل هذه؟"),
    ("workspace.delete.message", "Its sessions, items and notes will also be deleted. This cannot be undone.",
     "ستُحذف أيضاً جلساتها وعناصرها وملاحظاتها. لا يمكن التراجع عن ذلك."),
    ("workspaceEditor.editTitle", "Edit Workspace", "تعديل مساحة العمل"),
    ("workspaceEditor.kind", "Type", "النوع"),
    ("workspaceEditor.icon", "Icon", "الأيقونة"),
    ("workspaceEditor.settings", "Workspace Settings", "إعدادات مساحة العمل"),
    ("workspaceEditor.defaultSessionKind", "Default session type", "نوع الجلسة الافتراضي"),
    ("workspaceEditor.resumesLastSession", "Resume last session when opened", "استئناف آخر جلسة عند الفتح"),

    ("lens.title", "Lens", "العدسة"),
    ("lens.subtitle", "Understand text and links", "افهم النصوص والروابط"),
    ("lens.camera.explainTitle", "Use the camera for Lens?", "استخدام الكاميرا للعدسة؟"),
    ("lens.camera.explainMessage", "iOS will now ask for camera access. TaskLens uses the camera only when you take a photo for Lens to read. The photo is read on this device and isn't uploaded or kept unless you save a result.", "سيطلب iOS الآن الوصول إلى الكاميرا. يستخدم TaskLens الكاميرا فقط عندما تلتقط صورة لتقرأها العدسة. تُقرأ الصورة على هذا الجهاز ولا تُرفع ولا تُحفظ إلا إذا حفظت نتيجة."),
    ("lens.camera.notNow", "Not Now", "ليس الآن"),
    ("lens.camera.deniedTitle", "Camera access is off", "الوصول إلى الكاميرا متوقف"),
    ("lens.camera.deniedMessage", "To take a photo for Lens, allow Camera for TaskLens in iOS Settings. You can still choose a photo or a file.", "لالتقاط صورة للعدسة، اسمح بالكاميرا لتطبيق TaskLens من إعدادات iOS. ما زال بإمكانك اختيار صورة أو ملف."),
    ("lens.placeholder", "Paste or type text, a number or a link", "الصق أو اكتب نصاً أو رقماً أو رابطاً"),
    ("lens.input", "Content", "المحتوى"),
    ("lens.detectedType", "Detected type", "النوع المكتشف"),
    ("lens.detectedContent", "Detected Content", "المحتوى المكتشف"),
    ("lens.actions", "Actions", "الإجراءات"),
    ("lens.saved", "Saved", "تم الحفظ"),
    ("lens.image.section", "Read from an Image", "القراءة من صورة"),
    ("lens.image.photos", "Photos", "الصور"),
    ("lens.image.camera", "Camera", "الكاميرا"),
    ("lens.image.files", "Files", "الملفات"),
    ("lens.image.reading", "Reading the image…", "جارٍ قراءة الصورة…"),
    ("lens.image.found", "What I Found", "ما وجدته"),
    ("lens.image.nothing", "No text or codes found in this image.", "لم يُعثر على نص أو رموز في هذه الصورة."),
    ("lens.image.possible", "Possible match", "تطابق محتمل"),
    ("lens.image.possibleHint", "This part was hard to read. Check or correct it before using it.",
     "كان هذا الجزء صعب القراءة. تحقّق منه أو صحّحه قبل استخدامه."),
    ("lens.image.confirm", "Use This Text", "استخدم هذا النص"),
    ("lens.image.clear", "Clear Image", "مسح الصورة"),
    ("lens.image.failed", "TaskLens couldn't read this image.", "تعذّر على TaskLens قراءة هذه الصورة."),
    ("lens.image.privacy", "Images are read on this device. They aren't kept unless you save a result.",
     "تُقرأ الصور على هذا الجهاز، ولا يُحتفظ بها إلا إذا حفظت نتيجة."),
    ("lens.image.allText", "All Text", "كل النص"),
    ("lens.image.qr", "QR Code", "رمز QR"),
    ("lens.image.barcode", "Barcode", "باركود"),
    ("lens.image.documentTitle", "Title: %@", "العنوان: %@"),
    ("lens.image.paragraphs", "Paragraphs: %lld", "الفقرات: %lld"),
    ("lens.image.select", "Show actions", "عرض الإجراءات"),
    ("ai.section", "AI (Optional)", "الذكاء الاصطناعي (اختياري)"),
    ("ai.footer", "AI adds to Lens; it doesn't replace it. Nothing is sent until you tap Send.",
     "الذكاء الاصطناعي يضيف إلى العدسة ولا يحل محلها. لا يُرسل شيء حتى تضغط إرسال."),
    ("ai.taskLabel", "Task", "المهمة"),
    ("ai.task.summarize", "Summarize", "تلخيص"),
    ("ai.task.explain", "Explain", "شرح"),
    ("ai.task.translate", "Translate", "ترجمة"),
    ("ai.task.rewrite", "Rewrite", "إعادة صياغة"),
    ("ai.task.extract", "Extract Key Facts", "استخراج المعلومات المهمة"),
    ("ai.task.classify", "Classify", "تصنيف"),
    ("ai.task.generateNotes", "Make Notes", "إنشاء ملاحظات"),
    ("ai.task.generateQuestions", "Make Questions", "إنشاء أسئلة"),
    ("ai.task.compare", "Compare with Session", "مقارنة مع الجلسة"),
    ("ai.task.answer", "Ask a Question", "طرح سؤال"),
    ("ai.question", "Your question", "سؤالك"),
    ("ai.targetLanguage", "Translate Into", "الترجمة إلى"),
    ("ai.language.arabic", "Arabic", "العربية"),
    ("ai.language.english", "English", "الإنجليزية"),
    ("ai.includeSession", "Include this session's items", "تضمين عناصر هذه الجلسة"),
    ("ai.running", "Working…", "جارٍ العمل…"),
    ("ai.failed", "AI couldn't answer this time.", "تعذّر على الذكاء الاصطناعي الإجابة هذه المرة."),
    ("ai.send", "Send to AI", "إرسال إلى الذكاء الاصطناعي"),
    ("ai.retry", "Try AI Again", "إعادة محاولة الذكاء الاصطناعي"),
    ("ai.stillWorks", "Lens results and actions above still work.", "نتائج العدسة والإجراءات أعلاه ما زالت تعمل."),
    ("ai.unavailable.turnedOff", "AI is turned off in Settings.", "الذكاء الاصطناعي مُطفأ في الإعدادات."),
    ("ai.unavailable.deviceNotEligible", "This device can't run Apple Intelligence. You can add an AI server in Settings.",
     "هذا الجهاز لا يدعم Apple Intelligence. يمكنك إضافة خادم ذكاء اصطناعي من الإعدادات."),
    ("ai.unavailable.notEnabled", "Turn on Apple Intelligence in the Settings app to use AI.",
     "فعّل Apple Intelligence من تطبيق الإعدادات لاستخدام الذكاء الاصطناعي."),
    ("ai.unavailable.modelNotReady", "Apple Intelligence is still getting ready.", "Apple Intelligence ما زال قيد التجهيز."),
    ("ai.unavailable.offline", "No internet connection. The AI server can't be reached.",
     "لا يوجد اتصال بالإنترنت. لا يمكن الوصول إلى خادم الذكاء الاصطناعي."),
    ("ai.unavailable.notConfigured", "No AI is set up on this device.", "لا يوجد ذكاء اصطناعي مُعدّ على هذا الجهاز."),
    ("ai.disclosure.device", "Sends %lld characters to Apple Intelligence on this device. Nothing leaves your device.",
     "يرسل %lld حرفاً إلى Apple Intelligence على هذا الجهاز. لا يغادر شيء جهازك."),
    ("ai.disclosure.server", "Sends %lld characters over the internet to %@.",
     "يرسل %lld حرفاً عبر الإنترنت إلى %@."),
    ("ai.disclosure.session", "Includes titles of this session's items.", "يتضمن عناوين عناصر هذه الجلسة."),
    ("ai.disclosure.truncated", "Long text is shortened before sending.", "يُختصر النص الطويل قبل الإرسال."),
    ("ai.clear", "Clear Answer", "مسح الإجابة"),
    ("ai.answer.device", "AI Answer (on this device)", "إجابة الذكاء الاصطناعي (على هذا الجهاز)"),
    ("ai.answer.server", "AI Answer (from your AI server)", "إجابة الذكاء الاصطناعي (من خادمك)"),
    ("ai.suggestionsNote", "Suggested by AI. Nothing runs until you tap, and actions outside TaskLens ask first.",
     "اقتراحات من الذكاء الاصطناعي. لا يُنفّذ شيء حتى تضغط، والإجراءات خارج TaskLens تطلب تأكيدك أولاً."),
    ("ai.settings.enabled", "Use AI", "استخدام الذكاء الاصطناعي"),
    ("ai.status", "Status", "الحالة"),
    ("ai.status.ready", "Ready", "جاهز"),
    ("ai.settings.privacy",
     "What is sent: only the text you choose to send (Lens text, text read from an image or document, your question, and session titles if you include them). Never images or screen frames. When: only when you tap Send. Where: Apple Intelligence on this device first; your AI server only if you turn it on. Why: to answer the task you picked.",
     "ما الذي يُرسل: فقط النص الذي تختار إرساله (نص العدسة، أو النص المقروء من صورة أو مستند، وسؤالك، وعناوين الجلسة إذا ضمّنتها). لا تُرسل الصور أو إطارات الشاشة أبداً. متى: فقط عند الضغط على إرسال. إلى أين: Apple Intelligence على هذا الجهاز أولاً، وخادمك فقط إذا فعّلته. لماذا: لتنفيذ المهمة التي اخترتها."),
    ("ai.server.section", "AI Server (Optional)", "خادم ذكاء اصطناعي (اختياري)"),
    ("ai.server.address", "Server address (https://…)", "عنوان الخادم (https://…)"),
    ("ai.server.model", "Model name", "اسم النموذج"),
    ("ai.server.key", "API key", "مفتاح API"),
    ("ai.server.keySaved", "API key saved (enter a new one to replace it)", "مفتاح API محفوظ (أدخل مفتاحاً جديداً لاستبداله)"),
    ("ai.server.use", "Use This Server", "استخدام هذا الخادم"),
    ("ai.server.remove", "Remove Server", "إزالة الخادم"),
    ("ai.server.footer",
     "For devices without Apple Intelligence. Text you send goes to this server over HTTPS and its owner's privacy policy applies. The key stays in this device's Keychain.",
     "للأجهزة التي لا تدعم Apple Intelligence. النص الذي ترسله يذهب إلى هذا الخادم عبر HTTPS وتنطبق عليه سياسة خصوصية مالكه. يبقى المفتاح في سلسلة مفاتيح هذا الجهاز."),
    ("ai.server.invalid", "Enter an https:// address and a model name.", "أدخل عنواناً يبدأ بـ https:// واسم النموذج."),
    ("ai.history.keep", "Keep AI History", "الاحتفاظ بسجل الذكاء الاصطناعي"),
    ("ai.history", "AI History", "سجل الذكاء الاصطناعي"),
    ("ai.history.delete", "Delete AI History", "حذف سجل الذكاء الاصطناعي"),
    ("ai.history.footer", "History stays on this device so you can see what was sent. Turning it off deletes it.",
     "يبقى السجل على هذا الجهاز لترى ما أُرسل. إيقافه يحذفه."),
    ("ai.history.empty", "No AI requests yet.", "لا توجد طلبات ذكاء اصطناعي بعد."),
    ("actions.confirm.title", "Run this action?", "تنفيذ هذا الإجراء؟"),
    ("actions.confirm.message", "AI suggested it. It will open another app or change something outside TaskLens.",
     "اقترحه الذكاء الاصطناعي. سيفتح تطبيقاً آخر أو يغيّر شيئاً خارج TaskLens."),
    ("screenLens.section", "Read the Screen", "قراءة الشاشة"),
    ("screenLens.start", "Start Screen Lens", "بدء عدسة الشاشة"),
    ("screenLens.startAgain", "Start Screen Lens Again", "بدء عدسة الشاشة مجدداً"),
    ("screenLens.choosing", "Choose what to share…", "اختر ما تريد مشاركته…"),
    ("screenLens.capture", "Capture in 3 Seconds", "التقاط بعد 3 ثوانٍ"),
    ("screenLens.captureHint", "Tap Capture, then go to the screen you want read. You can also capture from the Live Activity.",
     "اضغط التقاط ثم انتقل إلى الشاشة التي تريد قراءتها. يمكنك أيضاً الالتقاط من النشاط المباشر."),
    ("screenLens.stop", "Stop", "إيقاف"),
    ("screenLens.reading", "Reading the screen…", "جارٍ قراءة الشاشة…"),
    ("screenLens.found", "Lens Found", "وجدت العدسة"),
    ("screenLens.nothing", "Nothing useful was found on this screen.", "لم يُعثر على شيء مفيد في هذه الشاشة."),
    ("screenLens.clear", "Delete Results", "حذف النتائج"),
    ("screenLens.privacy",
     "Screen Lens runs only after you tap Start and choose what to share. iOS shows its recording indicator while it runs. One frame is read on this device, then capture stops on its own. Frames are never saved or uploaded.",
     "تعمل عدسة الشاشة فقط بعد أن تضغط بدء وتختار ما تشاركه. يعرض iOS مؤشر التسجيل طوال عملها. يُقرأ إطار واحد على هذا الجهاز ثم يتوقف الالتقاط تلقائياً. لا تُحفظ الإطارات ولا تُرفع."),
    ("screenLens.unavailable", "Screen Lens needs iOS 27 or later.", "تحتاج عدسة الشاشة إلى iOS 27 أو أحدث."),
    ("screenLens.unavailableFooter",
     "Take a screenshot instead (side button and volume up), then choose it with Photos above. Lens reads it the same way.",
     "التقط لقطة شاشة بدلاً من ذلك (الزر الجانبي ورفع الصوت)، ثم اخترها من الصور في الأعلى. تقرأها العدسة بالطريقة نفسها."),
    ("screenLens.stopped.user", "Screen Lens stopped.", "توقفت عدسة الشاشة."),
    ("screenLens.stopped.timeLimit", "Screen Lens stopped on its own after 5 minutes.", "توقفت عدسة الشاشة تلقائياً بعد 5 دقائق."),
    ("screenLens.stopped.system", "iOS stopped the screen capture.", "أوقف iOS التقاط الشاشة."),
    ("screenLens.stopped.cancelled", "Nothing was shared.", "لم تتم مشاركة شيء."),
    ("screenLens.failed.start", "Screen capture couldn't start. It may be restricted on this device.",
     "تعذّر بدء التقاط الشاشة. قد يكون مقيّداً على هذا الجهاز."),
    ("screenLens.failed.noFrame", "No screen image arrived. Some apps protect their content from capture.",
     "لم تصل صورة للشاشة. بعض التطبيقات تحمي محتواها من الالتقاط."),
    ("screenLens.activity.live", "Screen Lens is on", "عدسة الشاشة تعمل"),
    ("screenLens.activity.countdown", "Capturing soon", "الالتقاط بعد لحظات"),
    ("screenLens.activity.stopsIn", "Stops in", "تتوقف بعد"),
    ("screenLens.activity.hint", "Go to the screen to read, then tap Capture.", "انتقل إلى الشاشة المراد قراءتها ثم اضغط التقاط."),

    ("clipboard.title", "Clipboard", "الحافظة"),
    ("clipboard.subtitle", "Paste to keep what you copied", "الصق للاحتفاظ بما نسخته"),
    ("clipboard.history", "History", "السجل"),
    ("clipboard.empty.title", "Nothing pasted yet", "لم يُلصق شيء بعد"),
    ("clipboard.empty.message", "Tap Paste to bring in what you copied. TaskLens never reads your clipboard on its own.",
     "اضغط لصق لإحضار ما نسخته. لا يقرأ TaskLens الحافظة من تلقاء نفسه."),
    ("clipboard.clear", "Clear History", "مسح السجل"),
    ("clipboard.saved", "Saved to TaskLens", "محفوظ في TaskLens"),

    ("action.copy", "Copy", "نسخ"),
    ("action.share", "Share", "مشاركة"),
    ("action.saveToSession", "Save", "حفظ"),
    ("action.openURL", "Open Link", "فتح الرابط"),

    # Phase 4: tools
    ("common.close", "Close", "إغلاق"),
    ("common.saved", "Saved", "تم الحفظ"),
    ("common.saveToSession", "Save to Session", "حفظ في الجلسة"),
    ("common.copied", "Copied", "تم النسخ"),
    ("common.matchCount", "Matches: %lld", "النتائج: %lld"),

    ("notes.new", "New Note", "ملاحظة جديدة"),
    ("notes.notFound", "This note is no longer available.", "هذه الملاحظة لم تعد متاحة."),
    ("notes.edit", "Edit Note", "تعديل الملاحظة"),
    ("notes.titlePlaceholder", "Title", "العنوان"),
    ("notes.bodyPlaceholder", "Write your note", "اكتب ملاحظتك"),
    ("notes.searchPrompt", "Search notes", "ابحث في الملاحظات"),
    ("notes.empty.title", "No notes yet", "لا توجد ملاحظات بعد"),
    ("notes.empty.message", "Tap + to write your first note.", "اضغط + لكتابة أول ملاحظة."),
    ("notes.pin", "Pin", "تثبيت"),
    ("notes.unpin", "Unpin", "إلغاء التثبيت"),
    ("notes.pinned", "Pinned", "مثبتة"),
    ("notes.attach", "Attach to Session", "إرفاق بجلسة"),
    ("notes.attached", "Attached to session", "أُرفقت بالجلسة"),
    ("notes.noSessions", "Start a session in a workspace to attach notes to it.",
     "ابدأ جلسة في مساحة عمل لإرفاق الملاحظات بها."),
    ("notes.untitled", "Untitled Note", "ملاحظة بدون عنوان"),
    ("notes.delete.title", "Delete this note?", "حذف هذه الملاحظة؟"),

    ("calculator.history", "History", "السجل"),
    ("calculator.history.empty", "Calculations you finish appear here.", "تظهر هنا العمليات التي تنهيها."),
    ("calculator.clearHistory", "Clear History", "مسح السجل"),
    ("calculator.copyResult", "Copy Result", "نسخ النتيجة"),
    ("calculator.sendToActions", "Send to Actions", "إرسال إلى الإجراءات"),
    ("calculator.useResult", "Use Result", "استخدام النتيجة"),
    ("calculator.error", "Cannot divide by zero", "لا يمكن القسمة على صفر"),
    ("calculator.key.add", "Plus", "زائد"),
    ("calculator.key.subtract", "Minus", "ناقص"),
    ("calculator.key.multiply", "Multiply", "ضرب"),
    ("calculator.key.divide", "Divide", "قسمة"),
    ("calculator.key.percent", "Percent", "نسبة مئوية"),
    ("calculator.key.equals", "Equals", "يساوي"),
    ("calculator.key.clear", "Clear", "مسح"),
    ("calculator.key.backspace", "Delete digit", "حذف رقم"),
    ("calculator.key.toggleSign", "Change sign", "تغيير الإشارة"),
    ("calculator.key.decimal", "Decimal point", "فاصلة عشرية"),

    ("browser.address", "Address", "العنوان"),
    ("browser.addressPrompt", "Enter a website address", "أدخل عنوان موقع"),
    ("browser.back", "Back", "رجوع"),
    ("browser.forward", "Forward", "تقدم"),
    ("browser.reload", "Reload", "إعادة التحميل"),
    ("browser.stop", "Stop", "إيقاف"),
    ("browser.tabs", "Tabs", "علامات التبويب"),
    ("browser.newTab", "New Tab", "علامة تبويب جديدة"),
    ("browser.closeTab", "Close Tab", "إغلاق علامة التبويب"),
    ("browser.empty.title", "Enter an address to start", "أدخل عنواناً للبدء"),
    ("browser.empty.message",
     "Pages open in a private session. Cookies and website data are cleared when TaskLens closes.",
     "تُفتح الصفحات في جلسة خاصة. تُمسح ملفات تعريف الارتباط وبيانات المواقع عند إغلاق TaskLens."),
    ("browser.saveURL", "Save Link to Session", "حفظ الرابط في الجلسة"),

    ("documents.import", "Import", "استيراد"),
    ("documents.importFiles", "From Files", "من الملفات"),
    ("documents.importPhotos", "From Photos", "من الصور"),
    ("documents.photoName", "Photo", "صورة"),
    ("documents.empty.title", "No documents", "لا توجد مستندات"),
    ("documents.empty.message", "Import a PDF, image, text or PowerPoint file. It stays on this device.",
     "استورد ملف PDF أو صورة أو ملفاً نصياً أو عرض PowerPoint. يبقى على هذا الجهاز."),
    ("documents.delete.title", "Delete this document?", "حذف هذا المستند؟"),
    ("documents.delete.message", "The copy stored in TaskLens will be removed.",
     "ستُحذف النسخة المحفوظة في TaskLens."),
    ("documents.openFailed", "This file could not be opened.", "تعذّر فتح هذا الملف."),
    ("documents.kind.powerpoint", "PowerPoint Presentation", "عرض PowerPoint تقديمي"),
    ("documents.powerpoint.notYet", "Presenting PowerPoint files isn't available yet. The file is saved in TaskLens.",
     "عرض ملفات PowerPoint غير متاح بعد. الملف محفوظ في TaskLens."),

    ("pdf.page", "Page %lld of %lld", "صفحة %lld من %lld"),
    ("pdf.previousPage", "Previous Page", "الصفحة السابقة"),
    ("pdf.nextPage", "Next Page", "الصفحة التالية"),
    ("pdf.goToPage", "Go to Page", "الانتقال إلى صفحة"),
    ("pdf.searchPrompt", "Search in document", "ابحث في المستند"),
    ("pdf.matchPosition", "%lld of %lld", "%lld من %lld"),
    ("pdf.noMatches", "No matches", "لا توجد نتائج"),
    ("pdf.previousMatch", "Previous Match", "النتيجة السابقة"),
    ("pdf.nextMatch", "Next Match", "النتيجة التالية"),
    ("pdf.extractText", "Extract Page Text", "استخراج نص الصفحة"),
    ("pdf.extractedText", "Page Text", "نص الصفحة"),
    ("pdf.noText", "This page has no selectable text. Open the document in Lens to read it on your device.",
     "لا تحتوي هذه الصفحة على نص قابل للتحديد. افتح المستند في العدسة لقراءته على جهازك."),
    ("pdf.lens", "Read with Lens", "القراءة بالعدسة"),
    ("pdf.saveText", "Save Text to Session", "حفظ النص في الجلسة"),

    ("presentation.present", "Present", "عرض تقديمي"),
    ("presentation.presentImages", "Present Images", "عرض الصور"),
    ("presentation.counter", "Slide %lld / %lld", "الشريحة %lld / %lld"),
    ("presentation.counterSpoken", "Slide %lld of %lld", "الشريحة %lld من %lld"),
    ("presentation.previous", "Previous Slide", "الشريحة السابقة"),
    ("presentation.next", "Next Slide", "الشريحة التالية"),
    ("presentation.goToSlide", "Go to Slide", "الانتقال إلى شريحة"),
    ("presentation.toggleControls", "Show or Hide Controls", "إظهار عناصر التحكم أو إخفاؤها"),
    ("presentation.loading", "Loading presentation…", "جارٍ تحميل العرض…"),
    ("presentation.slideFailed", "This slide could not be shown.", "تعذّر عرض هذه الشريحة."),
    ("presentation.empty.title", "No slides", "لا توجد شرائح"),
    ("presentation.empty.message", "This presentation has nothing to show.", "لا يحتوي هذا العرض على ما يُعرض."),
    ("presentation.unsupported.title", "This file can't be presented", "لا يمكن عرض هذا الملف"),
    ("presentation.unsupported.message", "Only PDFs and images can be presented.", "يمكن عرض ملفات PDF والصور فقط."),
    ("presentation.unreadable.title", "This presentation could not be opened", "تعذّر فتح هذا العرض"),
    ("presentation.unreadable.message", "A file may be missing, damaged or password protected.",
     "قد يكون أحد الملفات مفقوداً أو تالفاً أو محمياً بكلمة مرور."),
    ("presentation.autoPlay.start", "Start Auto Play", "بدء التشغيل التلقائي"),
    ("presentation.autoPlay.pause", "Pause Auto Play", "إيقاف التشغيل التلقائي مؤقتاً"),
    ("presentation.autoPlay.resume", "Resume Auto Play", "استئناف التشغيل التلقائي"),
    ("presentation.autoPlay.stop", "Stop Auto Play", "إنهاء التشغيل التلقائي"),
    ("presentation.autoPlay.interval", "Time per Slide", "مدة كل شريحة"),
    ("presentation.autoPlay.seconds", "%lld seconds", "%lld ثانية"),
    ("presentation.autoPlay.custom", "Custom…", "مدة مخصصة…"),
    ("presentation.autoPlay.customMessage", "Seconds per slide, from 1 to 3600.", "عدد الثواني لكل شريحة، من 1 إلى 3600."),

    ("image.recognizeText", "Recognize Text", "التعرف على النص"),
    ("image.resetZoom", "Reset Zoom", "إعادة ضبط التكبير"),

    ("text.searchPrompt", "Search in text", "ابحث في النص"),
    ("text.truncated", "Only the beginning of this file is shown.", "يُعرض جزء من بداية هذا الملف فقط."),
    ("text.copyAll", "Copy All", "نسخ الكل"),
    ("text.fontSize", "Text Size", "حجم النص"),
    ("text.monospaced", "Monospaced", "خط ثابت العرض"),
    ("text.smaller", "Smaller Text", "نص أصغر"),
    ("text.larger", "Larger Text", "نص أكبر"),
    ("text.saveText", "Save Text to Session", "حفظ النص في الجلسة"),

    # Phase 5: Context Engine, Action Engine, Smart Clipboard, Share Extension
    ("common.details", "Details", "التفاصيل"),

    ("category.plainText", "Text", "نص"),
    ("category.url", "Link", "رابط"),
    ("category.phone", "Phone Number", "رقم هاتف"),
    ("category.email", "Email Address", "بريد إلكتروني"),
    ("category.currency", "Amount of Money", "مبلغ مالي"),
    ("category.number", "Number", "رقم"),
    ("category.date", "Date", "تاريخ"),
    ("category.address", "Address", "عنوان"),
    ("category.json", "JSON", "JSON"),
    ("category.code", "Code", "شيفرة برمجية"),
    ("category.image", "Image", "صورة"),
    ("category.pdf", "PDF", "PDF"),
    ("category.document", "Document", "مستند"),
    ("category.unknown", "Unknown", "غير معروف"),

    ("action.call", "Call", "اتصال"),
    ("action.sendMessage", "Message", "رسالة"),
    ("action.sendEmail", "Email", "بريد إلكتروني"),
    ("action.addContact", "Add Contact", "إضافة جهة اتصال"),
    ("action.addToCalendar", "Create Calendar Event", "إنشاء حدث في التقويم"),
    ("action.openInMaps", "Open in Maps", "فتح في الخرائط"),
    ("action.calculate", "Calculate", "حساب"),
    ("action.convertCurrency", "Convert Currency", "تحويل العملة"),
    ("action.extractText", "Extract", "استخراج"),
    ("action.translate", "Translate", "ترجمة"),
    ("action.summarize", "Summarize", "تلخيص"),
    ("action.createReminder", "Create Reminder", "إنشاء تذكير"),
    ("action.createNote", "Create Note", "إنشاء ملاحظة"),
    ("action.search", "Search", "بحث"),
    ("action.askAI", "Ask AI", "اسأل الذكاء الاصطناعي"),

    ("actions.convert.title", "Convert Currency", "تحويل العملة"),
    ("actions.convert.message", "Converting %@. Enter what 1 unit of this currency is worth in yours. TaskLens has no live exchange rates, so it uses the rate you enter.", "تحويل %@. أدخل قيمة وحدة واحدة من هذه العملة بعملتك. لا يملك TaskLens أسعار صرف مباشرة، لذلك يستخدم السعر الذي تدخله."),
    ("actions.convert.rate", "Exchange rate", "سعر الصرف"),
    ("actions.convert.action", "Convert", "تحويل"),
    ("actions.convert.invalidRate", "Enter a rate above zero, for example 1310 or 0.92.", "أدخل سعراً أكبر من صفر، مثل 1310 أو 0.92."),
    ("actions.later", "Later", "لاحقاً"),
    ("actions.comingLater", "This action will be added in a later update.",
     "سيُضاف هذا الإجراء في تحديث لاحق."),
    ("actions.openApp", "Open TaskLens to do this. Save the item first, then use it from the app.",
     "افتح TaskLens لتنفيذ ذلك. احفظ العنصر أولاً ثم استخدمه من التطبيق."),
    ("actions.unavailable", "This action is not available for this content.",
     "هذا الإجراء غير متاح لهذا المحتوى."),
    ("actions.translateUnavailable", "Translation needs iOS 17.4 or later.",
     "تتطلب الترجمة iOS 17.4 أو أحدث."),
    ("actions.found", "Found in Content", "ما تم العثور عليه"),
    ("actions.inApp", "In App", "في التطبيق"),
    ("actions.recommended", "Recommended", "مقترحة"),
    ("actions.other", "More Actions", "إجراءات أخرى"),
    ("actions.showLess", "Show Less", "عرض أقل"),
    ("analysis.value", "Value", "القيمة"),
    ("analysis.confidence.high", "High confidence", "ثقة عالية"),
    ("analysis.confidence.medium", "Medium confidence", "ثقة متوسطة"),
    ("analysis.confidence.low", "Low confidence", "ثقة منخفضة"),

    # YouTube links: Open in YouTube, or play in YouTube's embedded player.
    ("action.openInYouTube", "Open in YouTube", "فتح في يوتيوب"),
    ("action.playVideo", "Play in TaskLens", "تشغيل في TaskLens"),
    ("analysis.youtubeVideo", "YouTube Video", "فيديو يوتيوب"),
    ("analysis.videoID", "Video ID", "معرّف الفيديو"),
    ("video.state.loading", "Loading the player…", "جارٍ تحميل المشغّل…"),
    ("video.state.ready", "Ready to play", "جاهز للتشغيل"),
    ("video.state.playing", "Playing", "قيد التشغيل"),
    ("video.state.paused", "Paused", "متوقف مؤقتاً"),
    ("video.state.buffering", "Loading…", "جارٍ التحميل…"),
    ("video.state.ended", "Ended", "انتهى"),
    ("video.error.offline", "The player needs an internet connection. The link stays saved and searchable offline.",
     "المشغّل يحتاج اتصالاً بالإنترنت. الرابط يبقى محفوظاً ويمكن البحث عنه بدون إنترنت."),
    ("video.error.embedding", "The video's owner doesn't allow playing it outside YouTube. Open it in YouTube instead.",
     "صاحب الفيديو لا يسمح بتشغيله خارج يوتيوب. افتحه في يوتيوب."),
    ("video.error.notFound", "This video was removed or is private.", "هذا الفيديو محذوف أو خاص."),
    ("video.error.other", "YouTube couldn't play this video here. Open it in YouTube instead.",
     "تعذّر على يوتيوب تشغيل هذا الفيديو هنا. افتحه في يوتيوب."),
    ("video.play", "Play", "تشغيل"),
    ("video.pause", "Pause", "إيقاف مؤقت"),
    ("video.back", "Back 10 seconds", "رجوع 10 ثوانٍ"),
    ("video.forward", "Forward 10 seconds", "تقديم 10 ثوانٍ"),
    ("video.note", "The video plays in YouTube's player while TaskLens is open, and pauses when you leave TaskLens. Picture in Picture for YouTube is in the YouTube app: open the video there, then leave the app while it plays.",
     "الفيديو يعمل في مشغّل يوتيوب ما دام TaskLens مفتوحاً، ويتوقف مؤقتاً عند الخروج من TaskLens. صورة داخل صورة ليوتيوب موجودة في تطبيق يوتيوب: افتح الفيديو هناك، ثم اخرج من التطبيق أثناء التشغيل."),

    ("lens.preview", "Preview", "معاينة"),

    ("clipboard.newContent", "You copied something new. Tap Paste to bring it in.",
     "نسخت شيئاً جديداً. اضغط لصق لإحضاره."),
    ("clipboard.privacyNote", "iOS asks before any app reads what you copied. TaskLens reads it only when you tap Paste.",
     "يسأل iOS قبل أن يقرأ أي تطبيق ما نسخته. يقرأه TaskLens فقط عندما تضغط لصق."),

    ("share.title", "TaskLens", "TaskLens"),
    ("share.loading", "Preparing items…", "جارٍ تجهيز العناصر…"),
    ("share.items", "Shared Items", "العناصر المشتركة"),
    ("share.destination", "Save To", "الحفظ في"),
    ("share.inbox", "Inbox", "الوارد"),
    ("share.save", "Save to Session", "حفظ في الجلسة"),
    ("share.saved", "Saved. It will appear in TaskLens the next time you open it.",
     "تم الحفظ. سيظهر في TaskLens عند فتحه في المرة القادمة."),
    ("share.nothingSupported", "None of these items can be saved.", "لا يمكن حفظ أي من هذه العناصر."),
    ("share.unsupported", "Not Supported", "غير مدعوم"),
    ("share.unsupported.type", "TaskLens can't open this type of item.", "لا يستطيع TaskLens فتح هذا النوع من العناصر."),
    ("share.unsupported.tooLarge", "This item is too large.", "هذا العنصر كبير جداً."),
    ("share.unsupported.unreadable", "This item couldn't be read.", "تعذّرت قراءة هذا العنصر."),
    ("share.unsupported.tooMany", "Only the first 10 items can be saved at once.",
     "يمكن حفظ أول 10 عناصر فقط في المرة الواحدة."),
    ("share.saveFailed", "The items could not be saved. Please try again.", "تعذّر حفظ العناصر. يرجى المحاولة مرة أخرى."),
    ("share.received", "Saved %lld shared items.", "تم حفظ %lld من العناصر المشتركة."),

    ("error.notFound", "This item no longer exists.", "هذا العنصر لم يعد موجوداً."),
    ("error.validation.emptyName", "Please enter a name.", "يرجى إدخال اسم."),
    ("error.validation.nameTooLong", "The name is too long.", "الاسم طويل جداً."),
    ("error.validation.emptyContent", "There is nothing to save.", "لا يوجد شيء لحفظه."),
    ("error.validation.contentTooLarge", "The content is too large.", "المحتوى كبير جداً."),
    ("error.validation.invalidURL", "The link is not valid.", "الرابط غير صالح."),
    ("error.validation.invalidExpression", "That is not a calculation TaskLens can do.", "هذه ليست عملية حسابية يستطيع TaskLens تنفيذها."),
    ("error.validation.outOfRange", "That value is out of range.", "هذه القيمة خارج النطاق المسموح."),
    ("error.validation.invalidPresentation", "This file isn't a valid PowerPoint presentation (.pptx).",
     "هذا الملف ليس عرض PowerPoint تقديمياً صالحاً بصيغة pptx."),
    ("error.state.sessionEnded", "This session has ended.", "انتهت هذه الجلسة."),
    ("error.state.sessionAlreadyActive", "This session is already active.", "هذه الجلسة نشطة بالفعل."),
    ("error.state.workspaceArchived", "This workspace is archived.", "مساحة العمل هذه مؤرشفة."),
    ("error.persistence", "Your data could not be saved. Please try again.",
     "تعذّر حفظ بياناتك. يرجى المحاولة مرة أخرى."),
    ("error.unsupportedContent", "This type of content is not supported yet.",
     "هذا النوع من المحتوى غير مدعوم بعد."),
    ("error.unavailable", "This feature is not available on this device.",
     "هذه الميزة غير متاحة على هذا الجهاز."),
    ("error.generic", "Please try again.", "يرجى المحاولة مرة أخرى."),
]


# App Intents metadata (titles, parameters, enum cases). The system reads these
# from the app's own catalog: App/TaskLens/Resources/Localizable.xcstrings.
APP_INTENT_STRINGS = [
    ("intent.startWorkspace.title", "Start Workspace", "بدء مساحة عمل"),
    ("intent.startWorkspace.description", "Opens your most recent workspace of a kind, or creates one.",
     "يفتح آخر مساحة عمل من نوع معيّن، أو ينشئ واحدة."),
    ("intent.openWorkspace.title", "Open Workspace", "فتح مساحة عمل"),
    ("intent.openWorkspace.description", "Opens a workspace in TaskLens.", "يفتح مساحة عمل في TaskLens."),
    ("intent.startSession.title", "Start Session", "بدء جلسة"),
    ("intent.startSession.description", "Starts a session in a workspace and opens it.", "يبدأ جلسة في مساحة عمل ويفتحها."),
    ("intent.openSession.title", "Open Session", "فتح جلسة"),
    ("intent.openSession.description", "Opens a session and continues where you stopped.", "يفتح جلسة ويتابع من حيث توقفت."),
    ("intent.saveContent.title", "Save Content", "حفظ محتوى"),
    ("intent.saveContent.description", "Saves text or a link to a session, or to the inbox when no session is active.",
     "يحفظ نصاً أو رابطاً في جلسة، أو في الوارد إذا لم تكن هناك جلسة نشطة."),
    ("intent.saveToSession.title", "Save to Session", "حفظ في جلسة"),
    ("intent.saveToSession.description", "Saves text or a link to your latest open session of a kind, starting one if needed.",
     "يحفظ نصاً أو رابطاً في آخر جلسة مفتوحة من نوع معيّن، ويبدأ جلسة إذا لزم."),
    ("intent.sendToTaskLens.title", "Send to TaskLens", "إرسال إلى TaskLens"),
    ("intent.sendToTaskLens.description", "Opens text or a link in Lens to see what you can do with it.",
     "يفتح نصاً أو رابطاً في العدسة لترى ما يمكنك فعله به."),
    ("intent.startLens.title", "Start Lens", "بدء العدسة"),
    ("intent.startLens.description", "Opens Lens to analyze text or a link.", "يفتح العدسة لتحليل نص أو رابط."),
    ("intent.openClipboard.title", "Open Clipboard", "فتح الحافظة"),
    ("intent.openClipboard.description", "Opens the TaskLens clipboard history.", "يفتح سجل حافظة TaskLens."),
    ("intent.createNote.title", "Create Note", "إنشاء ملاحظة"),
    ("intent.createNote.description", "Creates a note. With several lines, the first line is the title.",
     "ينشئ ملاحظة. إذا كانت عدة أسطر، يكون السطر الأول هو العنوان."),
    ("intent.calculate.title", "Calculate", "حساب"),
    ("intent.calculate.description", "Calculates an expression such as 12 × 3 + 4 on your device.",
     "يحسب عملية مثل 12 × 3 + 4 على جهازك."),
    ("intent.convertCurrency.title", "Convert Currency", "تحويل عملة"),
    ("intent.convertCurrency.description", "Multiplies an amount by the exchange rate you give. TaskLens does not download exchange rates.",
     "يضرب المبلغ في سعر الصرف الذي تحدده. لا يقوم TaskLens بتنزيل أسعار الصرف."),
    ("intent.stopSession.title", "Stop Session", "إيقاف الجلسة"),
    ("intent.stopSession.description", "Ends a TaskLens session and its Live Activity.", "ينهي جلسة TaskLens ونشاطها المباشر."),
    ("intent.param.sessionID", "Session ID", "معرّف الجلسة"),
    ("intent.captureScreen.title", "Capture Screen", "التقاط الشاشة"),
    ("intent.captureScreen.description", "Reads the screen once with the Screen Lens you started.",
     "يقرأ الشاشة مرة واحدة بعدسة الشاشة التي بدأتها."),
    ("intent.stopScreenLens.title", "Stop Screen Lens", "إيقاف عدسة الشاشة"),
    ("intent.stopScreenLens.description", "Stops screen capture.", "يوقف التقاط الشاشة."),
    ("intent.openDestination.title", "Open in TaskLens", "فتح في TaskLens"),

    ("intent.param.workspaceKind", "Workspace Kind", "نوع مساحة العمل"),
    ("intent.param.sessionKind", "Session Kind", "نوع الجلسة"),
    ("intent.param.workspace", "Workspace", "مساحة العمل"),
    ("intent.param.session", "Session", "الجلسة"),
    ("intent.param.text", "Text", "النص"),
    ("intent.param.expression", "Expression", "العملية"),
    ("intent.param.amount", "Amount", "المبلغ"),
    ("intent.param.rate", "Exchange Rate", "سعر الصرف"),
    ("intent.param.currency", "Target Currency Code", "رمز العملة الهدف"),
    ("intent.param.destination", "Destination", "الوجهة"),

    ("intent.prompt.text", "What should TaskLens save?", "ما الذي تريد حفظه في TaskLens؟"),
    ("intent.prompt.lensText", "What should TaskLens look at?", "ما الذي تريد أن يحلله TaskLens؟"),
    ("intent.prompt.note", "What should the note say?", "ماذا تريد أن تكتب في الملاحظة؟"),
    ("intent.prompt.expression", "What should TaskLens calculate?", "ما العملية التي تريد حسابها؟"),
    ("intent.prompt.amount", "What amount?", "ما المبلغ؟"),
    ("intent.prompt.rate", "What exchange rate?", "ما سعر الصرف؟"),
    ("intent.prompt.workspace", "Which workspace?", "أي مساحة عمل؟"),
    ("intent.prompt.session", "Which session?", "أي جلسة؟"),

    ("intent.type.workspace", "Workspace", "مساحة عمل"),
    ("intent.type.session", "Session", "جلسة"),
    ("intent.type.workspaceKind", "Workspace Kind", "نوع مساحة العمل"),
    ("intent.type.sessionKind", "Session Kind", "نوع الجلسة"),
    ("intent.type.destination", "TaskLens Tool", "أداة TaskLens"),

    ("intent.workspaceKind.study", "Study", "دراسة"),
    ("intent.workspaceKind.research", "Research", "بحث"),
    ("intent.workspaceKind.work", "Work", "عمل"),
    ("intent.workspaceKind.shopping", "Shopping", "تسوق"),
    ("intent.workspaceKind.developer", "Developer", "تطوير"),
    ("intent.sessionKind.general", "General", "عامة"),
    ("intent.sessionKind.research", "Research", "بحث"),
    ("intent.sessionKind.shopping", "Shopping", "تسوق"),
    ("intent.sessionKind.study", "Study", "دراسة"),
    ("intent.sessionKind.developer", "Developer", "تطوير"),
    ("intent.destination.lens", "Lens", "العدسة"),
    ("intent.destination.clipboard", "Clipboard", "الحافظة"),
    ("intent.destination.notes", "Notes", "الملاحظات"),
    ("intent.destination.calculator", "Calculator", "الحاسبة"),
]

# App Shortcut phrases. The English phrase is written in TaskLensShortcuts.swift
# and is the key; every phrase must name the app.
APP_SHORTCUT_PHRASES = [
    ("Send to ${applicationName}", "أرسل إلى ${applicationName}"),
    ("Analyze with ${applicationName}", "حلّل باستخدام ${applicationName}"),
    ("Start ${kind} workspace in ${applicationName}", "ابدأ مساحة ${kind} في ${applicationName}"),
    ("Start a workspace in ${applicationName}", "ابدأ مساحة عمل في ${applicationName}"),
    ("Save to ${sessionKind} session in ${applicationName}", "احفظ في جلسة ${sessionKind} في ${applicationName}"),
    ("Save to ${applicationName}", "احفظ في ${applicationName}"),
    ("Save to a session in ${applicationName}", "احفظ في جلسة في ${applicationName}"),
    ("Start ${applicationName} Lens", "ابدأ عدسة ${applicationName}"),
    ("Open Lens in ${applicationName}", "افتح العدسة في ${applicationName}"),
    ("Create ${applicationName} note", "أنشئ ملاحظة في ${applicationName}"),
    ("New note in ${applicationName}", "ملاحظة جديدة في ${applicationName}"),
    ("Open ${applicationName} clipboard", "افتح حافظة ${applicationName}"),
    ("Calculate with ${applicationName}", "احسب باستخدام ${applicationName}"),
    ("Open a session in ${applicationName}", "افتح جلسة في ${applicationName}"),
    ("Start a ${applicationName} session", "ابدأ جلسة في ${applicationName}"),
]

APP_RESOURCES = ROOT / "App/TaskLens/Resources"


def write_catalog(path, entries):
    catalog = {"sourceLanguage": "en", "strings": entries, "version": "1.0"}
    path.write_text(json.dumps(catalog, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def write_app_catalogs() -> None:
    keys = [k for k, _, _ in APP_INTENT_STRINGS]
    assert len(keys) == len(set(keys)), "duplicate app intent keys"
    write_catalog(APP_RESOURCES / "Localizable.xcstrings", {
        key: {
            "extractionState": "manual",
            "localizations": {
                "ar": {"stringUnit": {"state": "translated", "value": ar}},
                "en": {"stringUnit": {"state": "translated", "value": en}},
            },
        }
        for key, en, ar in APP_INTENT_STRINGS
    })
    phrases = [en for en, _ in APP_SHORTCUT_PHRASES]
    assert len(phrases) == len(set(phrases)), "duplicate phrases"
    assert all("${applicationName}" in en and "${applicationName}" in ar for en, ar in APP_SHORTCUT_PHRASES)
    write_catalog(APP_RESOURCES / "AppShortcuts.xcstrings", {
        en: {
            "extractionState": "manual",
            "localizations": {
                "ar": {"stringUnit": {"state": "translated", "value": ar}},
                "en": {"stringUnit": {"state": "translated", "value": en}},
            },
        }
        for en, ar in APP_SHORTCUT_PHRASES
    })


def case_name(key: str) -> str:
    parts = re.split(r"[.]", key)
    words = []
    for part in parts:
        words.append(part[0].upper() + part[1:])
    name = "".join(words)
    return name[0].lower() + name[1:]


def main() -> None:
    keys = [k for k, _, _ in STRINGS]
    assert len(keys) == len(set(keys)), "duplicate keys"

    catalog = {
        "sourceLanguage": "en",
        "strings": {
            key: {
                "extractionState": "manual",
                "localizations": {
                    "ar": {"stringUnit": {"state": "translated", "value": ar}},
                    "en": {"stringUnit": {"state": "translated", "value": en}},
                },
            }
            for key, en, ar in STRINGS
        },
        "version": "1.0",
    }
    (LOC / "Resources").mkdir(parents=True, exist_ok=True)
    (LOC / "Resources/Localizable.xcstrings").write_text(
        json.dumps(catalog, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )

    lines = [
        "// Generated by scripts/strings.py. Do not edit by hand.",
        "",
        "/// Every user-facing string key. The catalog is `Resources/Localizable.xcstrings`.",
        "public enum L10nKey: String, CaseIterable, Sendable {",
    ]
    for key in keys:
        lines.append(f'    case {case_name(key)} = "{key}"')
    lines.append("}")
    (LOC / "L10nKey.swift").write_text("\n".join(lines) + "\n", encoding="utf-8")
    write_app_catalogs()
    print(f"Wrote {len(keys)} keys, {len(APP_INTENT_STRINGS)} intent strings, {len(APP_SHORTCUT_PHRASES)} phrases")


if __name__ == "__main__":
    main()
